name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CMake setup
      run: /usr/bin/cmake -S . -B build
    - name: make
      run: /usr/bin/cmake --build build
